### ISSUE TITLE
Add single track TRAX routes from UTA

### ISSUE THREAD

**Issue by ZachBeck** [agrc/porter#152] opened 2021-08-17 16:09 UTC
# Summary

- **Proposed Readable Name**: Utah UTA Light Rail Routes
- **Proposed Internal Dataset Name**: LightRail_UTA
- **Proposed External Dataset Name**: uta_light_rail_routes 
- **Proposed Data Category**: TRANSPORTATION
- **Data Description**: Centerlines representing each TRAX route/line
- **Source Agency/Entity**: UTA
- **Contact**: Sumerset Ellis
- **Update Frequency**: As Needed

This is could be a can of worms... UTA has requested that our existing double track representation of TRAX routes be replaced with a version showing the centerline for each route. Where the different TRAX routes (R, B, G) share the same physical tracks the centerlines overlap. I think UTA would prefer that TRANSPORTATION.LightRail_UTA be replaced with the new centerline version but there is value (i.e. multi modal) in keeping our existing double track data. Does it make sense to have 2 versions of TRAX in the SGID or would it be better to have the double track version available in TRANSPORTATION.Railroads?

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

- [ ] Sweeper checks have run and passed (@gregbunce on `2021/00/00`)
- [ ] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce on `2021/00/00`)
- [ ] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on `2021/00/00`)

## Where is the data source

_Choose one._

- [ ] Internal SGID
- [ ] Farm from AGOL ([agol item url](??))

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [ ] Add data to the Internal SGID (@ZachBeck, completed: `2021/00/00`)
- [ ] Configure forklift for Farm from AGOL (@stdavis, completed: `2021/00/00`)
- [ ] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@ZachBeck, completed: `2021/00/00`)
- [ ] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@ZachBeck, completed: `2021/00/00`)
- [ ] Complete a `SGID.META.AGOLItems` record (@ZachBeck, completed: `2021/00/00`)
- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (@ZachBeck, completed: `2021/00/00`)

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/02/21`)
- [ ] ArcGIS Online via forklift (@stdavis on `2021/00/00`)
- [ ] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2021/00/00`)
- [ ] [Open Data](https://opendata.gis.utah.gov) (@steveoh on `2021/00/00`)
- [ ] [gis.utah.gov](https://gis.utah.gov/data) data pages (@steveoh on `2021/00/00`)
- [ ] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2021/00/00`)

## Notification

- [ ] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [ ] Cadastre Team (@rkelson)

**Comment by steveoh** [comment] 2021-08-18 15:42
@brigsz, @jacobdadams, @bertgranberg, and others... What are the pros and cons from the planning and transportation perspectives of this request? 

@ZachBeck I think that was a good recommendation to put the double track line work in the railroads dataset since it does sound like UTA is very interested in their data being single line.

**Comment by gregbunce** [comment] 2021-08-18 17:40
we should have a quick meeting with Summer at UTA to better understand the proposed changes.  what do you say @ZachBeck @jacobdadams @BGranberg - interested in joining?

**Comment by ZachBeck** [comment] 2021-08-18 18:06
I would vote for discussing it further in our data meeting (it's on the agenda) and if our decision is something that would give UTA heartburn then talk with Sumer.

**Comment by steveoh** [comment] 2021-08-23 15:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-09-06 15:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment] 2021-09-06 16:37
@ZachBeck What was the decision from the data meeting on this? I assume that this issue is holding up #153?

**Comment by ZachBeck** [comment] 2021-09-07 16:33
I think I'm the hold up. I'm not really thrilled about any of the options but I think replace the existing trax data with the centerline version and move our trax features into railroads is probably the best route. I'll get moving on this the week of the 13th when I'm back in town.

**Comment by steveoh** [comment] 2021-09-13 15:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @gregbunce has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-09-20 15:59
Everything ok @gbunce?

**Comment by gregbunce** [comment] 2021-09-20 16:03
Ha!  Yup. Sitting on an airplane trying to be productive for a moment using
a phone. Allz good.  I'll just get back to being unproductive.  I think it
will save me time.

**Comment by steveoh** [comment] 2021-10-18 15:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-11-01 15:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-11-08 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-11-22 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by stdavis** [comment] 2021-11-22 16:05
Any update on this @ZachBeck?

**Comment by ZachBeck** [comment] 2021-11-22 17:02
Today is the day

**Comment by steveoh** [comment] 2021-11-29 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-12-06 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-12-13 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-12-20 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2021-12-27 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2022-01-03 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2022-01-10 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2022-01-17 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2022-01-24 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2022-01-31 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment] 2022-02-07 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment] 2022-02-08 19:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment] 2022-02-14 16:00
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @ZachBeck has completed **0** out of **1** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @stdavis has completed **0** out of **1** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| gregbunce has completed **1** out of **1** tasks | :+1: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment] 2022-02-21 16:00
## conductor results for TRANSPORTATION.LightRail_UTA

| check | status |
| - | :-: |
| internal sgid | :+1: |
| meta table |  |
| - item id | :+1: |
| - item name | :+1: |
| - geometry type | :+1: |
| open sgid | :+1: |
| open data | :+1: |
| arcgis online | :+1: |
| stewardship |  |
| - Description | :+1: |
| - Data Source | :+1: |
| - Website URL | :+1: |
| - Endpoint | :+1: |
| - Data Type | :+1: |

**Comment by steveoh** [comment] 2022-02-21 16:29
Is https://opendata.gis.utah.gov/datasets/utah-uta-light-rail-routes/explore?location=40.645640%2C-111.914994%2C-1.00 the open data layer for this? I'm confused by the publish date of September 11, 2017.

**Comment by ZachBeck** [comment] 2022-02-28 16:47
I'll bring it up in this weeks data team meeting, it seems like the past couple times we were derailed by naming conventions. Part of me would rather delete the issue as well.

**Comment by steveoh** [comment] 2022-02-28 16:49
> Part of me would rather delete the issue as well.

Why do you want to delete the issue? The issue is letting us know we haven't finished the task yet.

**Comment by ZachBeck** [comment] 2022-02-28 16:54
I don't know... the single track vs double track representation seemed like splitting hairs to me. I'll try and get it wrapped up.

**Comment by gregbunce** [comment] 2022-02-28 17:19
i can't remember, has this data been added to Internal?

**Comment by ZachBeck** [comment] 2022-02-28 17:21
No. Every time we were close to doing something we started debating what the name should be.

**Comment by steveoh** [comment] 2022-02-28 17:21
The bot is showing this dataset as existing in internal. Is that not the case?

**Comment by ZachBeck** [comment] 2022-02-28 17:23
It's the 2 track version.

**Comment by steveoh** [comment] 2022-02-28 18:54
Oh ok shoot. I'll update the issue so the bot isn't confused. I used a new name `*_Carto` just to make it break.

**Comment by agrc-conductor** [comment] 2022-03-21 17:52
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **4** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **2** out of **6** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment] 2022-03-21 17:52
## conductor results for TRANSPORTATION.LightRail_Carto

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find TRANSPORTATION.LightRail_Carto in the worksheet |

**Comment by agrc-conductor** [comment] 2022-03-28 15:00
## conductor results for TRANSPORTATION.LightRail_Carto

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find TRANSPORTATION.LightRail_Carto in the worksheet |

**Comment by agrc-conductor** [comment] 2022-04-04 15:01
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **4** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **2** out of **6** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment] 2022-04-04 15:01
## conductor results for TRANSPORTATION.LightRail_Carto

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find TRANSPORTATION.LightRail_Carto in the worksheet |

**Comment by agrc-conductor** [comment] 2022-04-11 15:01
## conductor results for tasks - 152

| check | status |
| - | :-: |
| @gregbunce has completed **1** out of **4** tasks | :no_entry: |
| @ZachBeck has completed **0** out of **5** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **2** out of **6** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by agrc-conductor** [comment] 2022-04-11 15:01
## conductor results for TRANSPORTATION.LightRail_Carto

| check | status |
| - | :-: |
| internal sgid | :no_entry: |
| meta table |  |
| - item id | :no_entry: |
| - item name | :no_entry: |
| - geometry type | :no_entry: |
| stewardship | :no_entry: Did not find TRANSPORTATION.LightRail_Carto in the worksheet |

**Comment by steveoh** [comment] 2022-04-11 16:45
We should close this if we aren't going to do it. Or mark it as blocked or waiting or something instead of just ignoring all of these reminders.

**Comment by ZachBeck** [comment] 2022-04-11 17:04
At this point I vote to close it, it's kind of been a mess from the start. I'd be happy to revisit it if it becomes a problem for UTA later on.

**Closed** 2022-04-11 17:05 UTC
Labels: introduction, porter
